config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :destinations
  end

  resources :lists do
    resources :activities
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avtivity.rb
class Avtivity < ApplicationRecord
  belongs_to :lists
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :lists
end

app/models/list.rb
class List < ApplicationRecord
  has_one :destination
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
  end

  def show
  end

  def new
    @activities = Activity.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @activities = Activity.new(activity_params)
    if @activity.save
      redirect_to list_activities_path(@activity)
    else
      render partial: "form"
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to activities_path(@activity)
    else
      render partial: "form"
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def index
    @destinations = Destination.all
  end

  def show
  end

  def new
    @destination = Destination.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def update
    if @destination.update(destination_params)
      redirect_to destination_path(@destination)
    else
      render partial: "form"
    end
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      redirect_to destination_path(@destination)
    else
      render partial: "form"
    end
  end

  def destroy
    @destination.destroy
    redirect_to destinations_path
  end

  private

  def set_destination
    @destination = Destination.find(params[:id])
  end

  def destination_params
    params.require(:destination).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :set_list, only: [:show, :update, :edit, :destroy]

  def index
    @list = List.all
  end

  def show
  end

  def new
    @list = List.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render partial: "form"
    end
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list_)
    else
      render partial: "form"
    end
  end

  def destroy
    @list.destroy
    redirect_to list_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/activities/edit.html.erb
<h1>Activities#edit</h1>
<p>Find me in app/views/activities/edit.html.erb</p>

app/views/activities/index.html.erb
<h1>Activities#index</h1>
<p>Find me in app/views/activities/index.html.erb</p>

app/views/activities/new.html.erb
<h1>Activities#new</h1>
<p>Find me in app/views/activities/new.html.erb</p>

app/views/activities/show.html.erb
<h1>Activities#show</h1>
<p>Find me in app/views/activities/show.html.erb</p>

app/views/destinations/_form.html.erb
<h1><%= @destination.id ? 'Edit Destination' : 'Create Destination' %></h1>
<hr />
<%= form_for @destination do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/destinations/edit.html.erb
<h1>Destinations#edit</h1>
<p>Find me in app/views/destinations/edit.html.erb</p>

app/views/destinations/index.html.erb
<h1>Click a list to view destinations</h1>
 <%= link_to 'Create a new Destination', new_list_path %>
 <ul>
   <% @list.each do |list| %>
     <li><%= link_to list.name, list %></li>
   <% end %>
 </ul>

app/views/destinations/new.html.erb
<h1>Destinations#new</h1>
<p>Find me in app/views/destinations/new.html.erb</p>

app/views/destinations/show.html.erb
<h1><%= @list.name %></h1>
 <hr />
 <p>What would you like to do?</p>
 <%= link_to 'View Destination', sub_topics_path(@list) %>
 <br />
 <%= link_to 'Edit List', edit_sub_path(@list) %>
 <br />
 <%= link_to 'Delete List', @list, method: :delete, data: { confirm: 'Confirm delete?' }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit list' : 'Create list' %></h1>
<hr />
<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Bucket List</h1>
<hr />

<%= link_to 'Create a new list', new_list_path %>

<ul>
  <% @list.each do |list| %>
    <li>
      <%= link_to list.name, list %>
    </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create List' %></h1>
 <hr />

 <%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <%= f.submit %>
 <% end %>

app/views/lists/show.html.erb
<h1>Bucket List</h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Destination', lists_path(@list) %>
<br />
<%= link_to 'Edit Destination', edit_list_destination_path([@list, @destination]) %>
<br />
<%= link_to 'Delete Destination', @list, method: :delete %>